package Entity;
// Generated Mar 4, 2024, 10:11:08 AM by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;

/**
 * Timekeeper generated by hbm2java
 */
public class Timekeeper implements java.io.Serializable {

	private String timekeeperId;
	private Employee employee;
	private Timestamp dateTime;
	private char inOut;

	public Timekeeper() {
	}

	public Timekeeper(String timekeeperId, Employee employee, Timestamp dateTime, char inOut) {
		this.timekeeperId = timekeeperId;
		this.employee = employee;
		this.dateTime = dateTime;
		this.inOut = inOut;
	}

	public String getTimekeeperId() {
		return this.timekeeperId;
	}

	public void setTimekeeperId(String timekeeperId) {
		this.timekeeperId = timekeeperId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Timestamp getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Timestamp dateTime) {
		this.dateTime = dateTime;
	}

	public char getInOut() {
		return this.inOut;
	}

	public void setInOut(char inOut) {
		this.inOut = inOut;
	}

}
