package Entuty;
// Generated Mar 4, 2024, 10:11:08 AM by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * Sysdiagrams generated by hbm2java
 */
public class Sysdiagrams implements java.io.Serializable {

	private Integer diagramId;
	private Integer version;
	private Serializable name;
	private int principalId;
	private byte[] definition;

	public Sysdiagrams() {
	}

	public Sysdiagrams(Serializable name, int principalId, byte[] definition) {
		this.name = name;
		this.principalId = principalId;
		this.definition = definition;
	}

	public Integer getDiagramId() {
		return this.diagramId;
	}

	public void setDiagramId(Integer diagramId) {
		this.diagramId = diagramId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getPrincipalId() {
		return this.principalId;
	}

	public void setPrincipalId(int principalId) {
		this.principalId = principalId;
	}

	public byte[] getDefinition() {
		return this.definition;
	}

	public void setDefinition(byte[] definition) {
		this.definition = definition;
	}

}
